apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ include "gateway.name" . }}
spec:
  selector:
    istio: ingress
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - descomplica.dev
