version: '3.9'

services:
  date-api:
    build: ./api
    container_name: date-api
    hostname: date-api
    restart: always
    ports:
      - 3000:3000
    environment:
      PORT: 3000

  web:
    build: ./web
    container_name: website
    hostname: website
    restart: always
    ports:
      - 80:3000
    environment:
      PORT: 3000
      DATE_API_URL: http://date-api:3000