version: '3.9'

services:
  descomplica-api:
    build: ./api
    container_name: descomplica-api
    hostname: descomplica-api
    restart: always
    ports:
      - 3000:3000
    environment:
      PORT: 3000

  descomplica-web:
    build: ./web
    container_name: descomplica-web
    hostname: descomplica-web
    restart: always
    ports:
      - 80:3000
    environment:
      PORT: 3000