apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "api.fullname" . }}
  labels:
    {{- include "api.labels" . | nindent 4 }}
  namespace: {{ include "api.fullname" . }}
spec:
  hosts:
    - descomplica.dev
  gateways:
    - istio-ingress/descomplica-gateway
  http:
    - route:
      - destination:
          host: "{{ include "api.fullname" . }}.{{ include "api.fullname" . }}.svc.cluster.local"
          port: 
            number: 3000