name: WEB Application CI

on: 
  push:
  pull_request:
    branches:    
      - 'main'
    paths:
      - 'applications/web/*'

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      DOCKER_IMAGE: 'matheusmazzoni/descomplica-web:${{ github.sha }}'
    defaults:
      run:
        working-directory: applications/web/
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Load Docker cache layers
      uses: satackey/action-docker-layer-caching@v0.0.11
      continue-on-error: true

    - name: Build Docker image
      run: docker image build . --file Dockerfile --tag ${{ env.DOCKER_IMAGE }}

    - name: Test Application
      run: docker container run --rm ${{ env.DOCKER_IMAGE }} yarn test
      # Continuar, pois não foi implementado tests com jest
      continue-on-error: true
    
    - name: Push to docker repository
      run: docker image push ${{ env.DOCKER_IMAGE }}